######################################################################
# WARNING: 'lib/Config_git.pl' is generated by make_patchnum.pl
#          DO NOT EDIT DIRECTLY - edit make_patchnum.pl instead
######################################################################
$Config::Git_Data=<<'ENDOFGIT';
git_commit_id='79a7b254d85a10b65126ad99bf10e70480569d68'
git_describe='79a7b254d85a10b65126ad99bf10e70480569d68'
git_branch='pull-request-'
git_uncommitted_changes=''
git_commit_id_title='Snapshot of:'
git_commit_date='2021-05-20 19:31:26 +0200'
git_snapshot_date='2021-05-20 19:31:26 +0200'

ENDOFGIT
