#!/bin/sh
#
# conntrackd	daemon for netfilter connection tracking.
#
# chkconfig: - 97 03
# description: This is a daemon for replicating connection state across two machines.
# processname: conntrackd
# pidfile: /run/conntrackd.pid
# config: /etc/conntrackd/conntrackd.conf
#
### BEGIN INIT INFO
# Provides: conntrackd
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Should-Start: $named
# Should-Stop: $named
# Default-Start: 3 4 5
# Default-Stop: 0 1 6
# Short-Description: daemon for netfilter connection tracking
# Description: This is a daemon for replicating connection state across two machines.
### END INIT INFO


# Do not load RH compatibility interface.
WITHOUT_RC_COMPAT=1

# Source function library.
. /etc/init.d/functions

PIDFILE=/run/conntrackd.pid
CONNTRACKD_OPTIONS=""
CONNTRACKD_CONF="/etc/conntrackd/conntrackd.conf"
CONNTRACKD_LOCKFILE="/run/lock/conntrackd.lock"

SourceIfNotEmpty /etc/sysconfig/conntrackd
LOCKFILE=$CONNTRACKD_LOCKFILE

RETVAL=0

start()
{
	start_daemon --pidfile "$PIDFILE" --lockfile "$LOCKFILE" --expect-user root -- conntrackd -d $CONNTRACKD_OPTIONS -C $CONNTRACKD_CONF
	RETVAL=$?
	return $RETVAL
}

stop()
{
	stop_daemon --pidfile "$PIDFILE" --lockfile "$LOCKFILE" --expect-user root -- conntrackd
	RETVAL=$?
	return $RETVAL
}

restart()
{
	stop
	start
}

reload()
{
	msg_reloading conntrackd
	stop_daemon --pidfile "$PIDFILE" --expect-user root -HUP -- conntrackd
	RETVAL=$?
	return $RETVAL
}

# See how we were called.
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload)
		reload
		;;
	restart)
		restart
		;;
	condstop)
		if [ -e "$LOCKFILE" ]; then
			stop
		fi
		;;
	condrestart)
		if [ -e "$LOCKFILE" ]; then
			restart
		fi
		;;
	condreload)
		if [ -e "$LOCKFILE" ]; then
			reload
		fi
		;;
	status)
		status --pidfile "$PIDFILE" --expect-user root -- conntrackd
		RETVAL=$?
		;;
	*)
		msg_usage "${0##*/} {start|stop|reload|restart|condstop|condrestart|condreload|status}"
		RETVAL=1
esac

exit $RETVAL
