# USB Flash note: write the contents including .disk/ onto
# an ext2 formatted partition with "altinst" filesystem label
# (see also http://altlinux.org/write.sh)

default=@default@
timeout=@timeout@
